apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jizt.name" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "jizt.name" . }}
    chart: {{ include "jizt.chart" . }}
    release: {{ $.Release.Name }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.ingress.paths.v1 }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.dispatcher.name }}-service
            port:
              number: {{ .Values.dispatcher.ports.svc }}