{{- include "jiztlibchart.deployment" (list . "jizt.dispatcher-deployment") -}}
{{- define "jizt.dispatcher-deployment" -}}
metadata:
  name: {{ .Values.dispatcher.name }}-deployment
  labels:
    microservice: {{ .Values.dispatcher.name }}
spec:
  selector:
    matchLabels:
      microservice: {{ .Values.dispatcher.name }}
  template:
    metadata:
      labels:
        microservice: {{ .Values.dispatcher.name }}
    spec:
      containers:
      - name: {{ .Values.dispatcher.name }}
        image: {{ .Values.dispatcher.image }}
        args: ["-d"]  # uncomment for debug mode
        env:
        - name: FLASK_SERVER_PORT
          value: "{{ .Values.dispatcher.ports.container }}"
        - name: PG_HOST
          value: {{ .Values.postgres.host }}
        - name: PG_DBNAME
          value: {{ .Values.postgres.dbName }}
        - name: PG_SECRET_PATH
          value: {{ .Values.postgres.secret.mountPath }}
        - name: PG_USERNAME_FILE
          value: {{ .Values.postgres.secret.usernameFile }}
        - name: PG_PASSWORD_FILE
          value: {{ .Values.postgres.secret.passwordFile }}
        volumeMounts:
        - name: {{ .Values.postgres.secret.volumeName }}
          mountPath: {{ .Values.postgres.secret.mountPath }}
          readOnly: true
        ports:
        - containerPort: {{ .Values.dispatcher.ports.container }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.dispatcher.ports.container }}
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.dispatcher.ports.container }}
          initialDelaySeconds: 5
          periodSeconds: 15
      volumes:
      - name: {{ .Values.postgres.secret.volumeName }}
        secret:
          secretName: {{ .Values.postgres.secret.secretName }}
{{- end -}}