{{- include "jiztlibchart.service" (list . "jizt.dispatcher-service") -}}
{{- define "jizt.dispatcher-service" -}}
metadata:
  name: {{ .Values.dispatcher.name }}-service
  labels:
    microservice: {{ .Values.dispatcher.name }}
spec:
  selector:
    microservice: {{ .Values.dispatcher.name }}
  ports:
  - port: {{ .Values.dispatcher.ports.svc }}
    targetPort: {{ .Values.dispatcher.ports.container }}
{{- end -}}