apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "jizt.name" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "jizt.name" . }}
    chart: {{ include "jizt.chart" . }}
    release: {{ $.Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: api-jizt-it
    networking.gke.io/managed-certificates: jizt-tls
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
        - path: {{ .Values.ingress.paths.v1 }}
          backend:
            serviceName: {{ .Values.dispatcher.name }}-service
            servicePort: {{ .Values.dispatcher.ports.svc }}