apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "jizt.name" . }}
    chart: {{ include "jizt.chart" . }}
    release: "{{ $.Release.Name }}"
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.replicas }}
    resources:
      requests:
        memory: {{ .Values.kafka.memoryRequests }}
      limits:
        memory: {{ .Values.kafka.memoryLimits }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      auto.create.topics.enable: {{ .Values.kafka.config.autoCreateTopics }}
      message.max.bytes: {{ .Values.kafka.config.messageMaxBytes }}
      offsets.topic.replication.factor: {{ .Values.kafka.config.topicReplicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.kafka.config.logReplicationFactor }}
      transaction.state.log.min.isr: {{ .Values.kafka.config.logMinIsr }}
      log.message.format.version: {{ .Values.kafka.config.logMessageFormatVersion }}
    storage:
      type: ephemeral
  zookeeper:
    replicas: {{ .Values.kafka.zookeeper.replicas }}
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}