apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.modelsPV.name }}-pv
  labels:
    app: {{ include "jizt.name" . }}
    chart: {{ include "jizt.chart" . }}
    release: "{{ $.Release.Name }}"
spec:
  storageClassName: {{ .Values.modelsPV.name }}
  capacity:
    storage: {{ .Values.modelsPV.capacity.storage }}
  accessModes:
  - ReadOnlyMany
  claimRef:
    namespace: default
    name: {{ .Values.modelsPV.name }}-pvc
  persistentVolumeReclaimPolicy: {{ .Values.modelsPV.pvReclaimPolicy }}
  gcePersistentDisk:
    pdName: {{ .Values.modelsPV.gcePersistentDisk.pdName }}
    fsType: {{ .Values.modelsPV.gcePersistentDisk.fsType }} 

  # csi:
  #   driver: {{ .Values.modelsPV.csi.driver }}
  #   volumeHandle: {{ .Values.modelsPV.csi.volumeHandle }}
  #   readOnly: {{ .Values.modelsPV.csi.readOnly }}
  #   fsType: {{ .Values.modelsPV.csi.fsType }}