{{- include "jiztlibchart.deployment" (list . "jizt.textPostprocessor-deployment") -}}
{{- define "jizt.textPostprocessor-deployment" -}}
metadata:
  name: {{ .Values.textPostprocessor.name }}-deployment
  labels:
    microservice: {{ .Values.textPostprocessor.name }}
spec:
  selector:
    matchLabels:
      microservice: {{ .Values.textPostprocessor.name }}
  template:
    metadata:
      labels:
        microservice: {{ .Values.textPostprocessor.name }}
    spec:
      containers:
      - name: {{ .Values.textPostprocessor.name }}
        image: {{ .Values.textPostprocessor.image }}
        args: ["-d"]  # uncomment for debug mode
        ports:
        - containerPort: {{ .Values.textPostprocessor.ports.container }}
        resources:
          requests:
            memory: {{ .Values.textPostprocessor.requests.memory }}
            cpu: {{ .Values.textPostprocessor.requests.cpu }}
          limits:
            memory: {{ .Values.textPostprocessor.limits.memory }}
            cpu: {{ .Values.textPostprocessor.limits.cpu }}
{{- end -}}